class GomokuBoard:
    def __init__(self, size=15): ...
    def make_move(self, row, col): ...
    def is_valid_move(self, row, col): ...
    def check_winner(self): ...
    def get_available_moves(self): ...
    def display(self): ...